### PR TITLE
support to get into recoery mode

### PR DESCRIPTION
**Pull request by xiaopingx**

### CODE REVIEW

**Comment by xiaopingx** [comment]
https://github.com/android-ia/system-core/pull/5

**Comment by xiaopingx** [comment]
The two patches include save adb reboot fastboot/recovery variables into misc partition and solve the problem like "recovery[1958]: segfault at 0 ip 000000000043c777 sp 00007ffff40aaca8 error 4 in recovery[400000+199000]" that couldn't able to get into recovery mode homescreen.

**Comment by xihua-chen** [comment]
hold on this patch first, some patches related with drm

**Comment by xiaopingx** [comment]
https://github.com/android-ia/device-intel-common/pull/6
https://github.com/android-ia/device-androidia/pull/62
https://github.com/android-ia/device-androidia-mixins/pull/50

**Comment by sgnanase** [comment]
Merged...

**Pull request merged**
