### PR TITLE
adb reboot bootloader could work on Joule

### PR DESCRIPTION
**Pull request by xiaopingx**
we can use
		adb reboot bootloader
		adb reboot-bootloader
	boot into fastboot mode

	Bug ID: https://01.org/jira/browse/AIA-159
	Test: I test it on Joule board, it can work well, but another modes which
	still can't work now, I will check them further.

	Signed-off-by: hu,xiaopingx <xiaopingx.hu@intel.com>
	Signed-off-by: Chen,Xihua <xihua.chen@intel.com>

### CODE REVIEW

**Comment by xiaopingx** [comment]
hi, everyone:
                  for now, we can use adb reboot bootloader or adb reboot-bootloader to boot fastboot mode

**Comment by kalyankondapally** [comment]
@Kishore409 can u test with Joule board

**Comment by Kishore409** [comment]
@kalyankondapally tested on Joule, "adb reboot bootloader "is booting to fastboot mode

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
