### PR TITLE
Write boot command variables into misc partition

### PR DESCRIPTION
**Pull request by zhoulihuagithub**
Update write_reboot_bootloader() funtion to support
different boot reason, such as bootloader, fastboot,
and recovery.

Jira: None.
Test: Test it on Joule and KBL NUC.

Signed-off-by: Zhou, Lihua <lihuax.zhou@intel.com>

### CODE REVIEW

**Comment by android-ia-srv** [comment]
Commit message is verified for commit id:  https://github.com/android-ia/bootable-recovery/pull/6/commits/ebc4abe34f4b2db83f64d23d55150fbff62df338 <br>

**Comment by codernavi18** [comment]
I can see a build failure. As I can see that you have added a new parameter to the function `write_reboot_bootloader`, so please make sure that you have made the relevant change to all the function calls to this function.

e.g 
`system/core/init/reboot.cpp:447:22: error: no matching function for call to 'write_reboot_bootloader'.`

**Comment by zhoulihuagithub** [comment]
@codernavi18 
In fact, I submitted another patch as below which call write_reboot_bootloader() at the same time. How to link the two patches to merge them together?
https://github.com/android-ia/system-core/pull/11

**Comment by zhoulihuagithub** [comment]
The relevant patch below needs to be mergered together.
https://github.com/android-ia/system-core/pull/11/

**Comment by codernavi18** [comment]
@zhoulihuagithub I have removed my review comments, after seeing the referenced build. 
You can always attach references to related pull requests, in order to help the maintainers understand that they should be merged together. However, in case they belong to the same project and if possible, try to squash changes into the same pull request (PR), as long as atomicity is not affected.

**Pull request closed without merging**
